
spring:
  application:
    name: darackbang-admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: darackbangadmin
    password: darackbangadmin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: true

logging:
  level:
    root: info
    com.lab.darackbang.*: trace
    org.springframework.security.web : trace

com:
  lab:
    upload:
      path: C:\darackbang\upload

server:
  servlet:
    session:
      timeout: 30m  # 세션 타임아웃을 30분으로 설정
  port: 8080