
spring:
  application:
    name: darackbang-admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.231:1521:xe
    username: darackbangadmin
    password: darackbangadmin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.springframework.orm.hibernate5.SpringJtaPlatform
        format_sql: true
        dialect: org.hibernate.community.dialect.OracleLegacyDialect
    show-sql: true
    open-in-view: true

logging:
  level:
    root: info
    com.lab.darackbang.*: trace
    org.springframework.security.web : trace

com:
  lab:
    upload:
      path: C:\darackbang\upload

server:
  servlet:
    session:
      timeout: 30m  # 세션 타임아웃을 30분으로 설정
  port: 8081